server.port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/cfg
            - classpath:/cfg/{application}
            - classpath:/cfg/{application}-{profile}
  profiles:
    active: native